TP-620: Prevent using "from string" converters when writing db data
* Explicitly sets the type of converion expected by the ymer built-in custom converters.
* Reason for setting is to prevent that the "from string to (something)" converters are used by default when writing data to the db, such as the `LocalDateTimeReadConverter`.
* Now, instead, only the `WritingConverter`s will be used when writing data. This means that string data will not get mangled by the custom converters.
* This commit prevents exceptions such as the following:

```
2021-03-04 13:52:04,267 [GS-LRMI Connection-pool-1-thread-2] ERROR RethrowsTransientDocumentWriteExceptionHandler Exception when executing mirror command! Attempted operation: Operation: INSERT, objects: [[SpaceFilePublicationEvent{id='A1^1111111111111111^3', time=2021-03-04T13:52:02.405924, file='accounts'}]] - This command will be ignored but the rest of the commands in this bulk will be attempted. This can lead to data inconsistency in the mongo database. Must be investigated ASAP. If this error was preceeded by a TransientDocumentWriteException the cause might be that we reattempt already performed operations, which might be fine.
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.time.LocalDateTime] for value 'accounts'; nested exception is java.time.format.DateTimeParseException: Text 'accounts' could not be parsed at index 0
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleWrite(MappingMongoConverter.java:869) ~[spring-data-mongodb-2.0.14.RELEASE.jar:2.0.14.RELEASE]
	...
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:79) ~[spring-data-mongodb-2.0.14.RELEASE.jar:2.0.14.RELEASE]
	at com.avanza.ymer.DocumentConverter$MongoConverterDocumentConverter.convertToBsonDocument(DocumentConverter.java:132) ~[ymer-14.5.0.jar:14.5.0]
	at com.avanza.ymer.DocumentConverter.convertToBsonDocument(DocumentConverter.java:65) ~[ymer-14.5.0.jar:14.5.0]
	at com.avanza.ymer.SpaceMirrorContext.toVersionedDocument(SpaceMirrorContext.java:112) ~[ymer-14.5.0.jar:14.5.0]
	at com.avanza.ymer.MirroredObjectWriter$MongoCommand.execute(MirroredObjectWriter.java:161) [ymer-14.5.0.jar:14.5.0]
	at com.avanza.ymer.MirroredObjectWriter.insertAll(MirroredObjectWriter.java:139) [ymer-14.5.0.jar:14.5.0]
	at com.avanza.ymer.MirroredObjectWriter.executeBulk(MirroredObjectWriter.java:77) [ymer-14.5.0.jar:14.5.0]
	at com.avanza.ymer.YmerSpaceSynchronizationEndpoint.onOperationsBatchSynchronization(YmerSpaceSynchronizationEndpoint.java:44) [ymer-14.5.0.jar:14.5.0]
	at com.gigaspaces.internal.sync.mirror.MirrorBulkExecutor.execute(MirrorBulkExecutor.java:73) [xap-datagrid-14.5.0-patch-h-1.jar:?]
	at com.gigaspaces.internal.sync.mirror.MirrorReplicationInHandler.execute(MirrorReplicationInHandler.java:127) [xap-datagrid-14.5.0-patch-h-1.jar:?]
	at com.gigaspaces.internal.sync.mirror.MirrorReplicationInBatchConsumptionHandler.consumePendingOperationsInBatch(MirrorReplicationInBatchConsumptionHandler.java:44) [xap-datagrid-14.5.0-patch-h-1.jar:?]
	...
	at com.gigaspaces.lrmi.nio.Pivot$ChannelEntryTask.run(Pivot.java:173) [xap-datagrid-14.5.0-patch-h-1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.time.format.DateTimeParseException: Text 'accounts' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[?:?]
	at se.avanzabank.example.persistence.mirror.LocalDateTimeReadConverter.convert(LocalDateTimeReadConverter.java:12) ~[example-pu-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at se.avanzabank.example.persistence.mirror.LocalDateTimeReadConverter.convert(LocalDateTimeReadConverter.java:8) ~[example-pu-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:385) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	... 41 more
```