TP-833: Fully create MongoConverter in unit tests
* Makes the app-provided instance of `MongoConverter` be fully instantiated with its internal `conversionService` field when running unit tests using the converters.
* Fixes issue where, if an app provided an instance of `MongoConverter` that is not created in a spring context but only programmatically in a unit test, the tests that inherit from `YmerConverterTestBase` would not work.
* Resolves the following exception, as seen when running unit tests on an app that provides an instance of `MongoConverter` where `.afterPropertiesSet()` has not yet been called:
```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.time.Instant] to type [java.lang.String]	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleWrite(MappingMongoConverter.java:911)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeSimpleInternal(MappingMongoConverter.java:891)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeProperties(MappingMongoConverter.java:552)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:526)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:499)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:443)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:80)
	at com.avanza.ymer.DocumentConverter$MongoConverterDocumentConverter.convertToBsonDocument(DocumentConverter.java:118)
	at com.avanza.ymer.DocumentConverter.convertToBsonDocument(DocumentConverter.java:60)
	at com.avanza.ymer.TestDocumentConverter.convertToBsonDocument(TestDocumentConverter.java:37)
	at com.avanza.ymer.YmerConverterTestBase.serializationTest(YmerConverterTestBase.java:89)
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.time.Instant] to type [java.lang.String]	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleWrite(MappingMongoConverter.java:911)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeSimpleInternal(MappingMongoConverter.java:891)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeProperties(MappingMongoConverter.java:552)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:526)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:499)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:443)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:80)
	at com.avanza.ymer.DocumentConverter$MongoConverterDocumentConverter.convertToBsonDocument(DocumentConverter.java:118)
	at com.avanza.ymer.DocumentConverter.convertToBsonDocument(DocumentConverter.java:60)
	at com.avanza.ymer.TestDocumentConverter.convertToBsonDocument(TestDocumentConverter.java:37)
	at com.avanza.ymer.YmerConverterTestBase.testFailsIfSpringDataIdAnnotationNotDefinedForSpaceObject(YmerConverterTestBase.java:106)
```